<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.9" tiledversion="1.9.2" name="morgTileSet" tilewidth="16" tileheight="16" tilecount="88" columns="11">
 <image source="morgTileSet.png" width="176" height="128"/>
 <tile id="0" type="wall"/>
 <tile id="1" type="wall"/>
 <tile id="2" type="wall"/>
 <tile id="3" type="wall"/>
 <tile id="4" type="cellcorpse"/>
 <tile id="5" type="cellcorpse"/>
 <tile id="6" type="surgicaltable"/>
 <tile id="7" type="surgicaltable"/>
 <tile id="8" type="surgicaltable"/>
 <tile id="9" type="surgicaltable"/>
 <tile id="11" type="wall"/>
 <tile id="12" type="wall"/>
 <tile id="13" type="wall"/>
 <tile id="14" type="wall"/>
 <tile id="15" type="cellcorpse"/>
 <tile id="16" type="cellcorpse"/>
 <tile id="17" type="surgicaltable"/>
 <tile id="18" type="surgicaltable"/>
 <tile id="19" type="surgicaltable"/>
 <tile id="20" type="surgicaltable"/>
 <tile id="22" type="wall"/>
 <tile id="23" type="wall"/>
 <tile id="24" type="wall"/>
 <tile id="25" type="wall"/>
 <tile id="26" type="electricalpanel"/>
 <tile id="27" type="electricalpanel"/>
 <tile id="28" type="surgicaltable"/>
 <tile id="29" type="surgicaltable"/>
 <tile id="30" type="surgicaltable"/>
 <tile id="31" type="surgicaltable"/>
 <tile id="33" type="wall"/>
 <tile id="34" type="wall"/>
 <tile id="35" type="wall"/>
 <tile id="36" type="wall"/>
 <tile id="37" type="electricalpanel"/>
 <tile id="38" type="electricalpanel"/>
 <tile id="39" type="surgicaltable"/>
 <tile id="40" type="surgicaltable"/>
 <tile id="41" type="surgicaltable"/>
 <tile id="42" type="surgicaltable"/>
 <tile id="44" type="wall"/>
 <tile id="45" type="wall"/>
 <tile id="46" type="wall"/>
 <tile id="47" type="wall"/>
 <tile id="48" type="openelectricalpanel"/>
 <tile id="49" type="openelectricalpanel"/>
 <tile id="50" type="surgicaltable"/>
 <tile id="51" type="surgicaltable"/>
 <tile id="52" type="surgicaltable"/>
 <tile id="53" type="surgicaltable"/>
 <tile id="55" type="ground"/>
 <tile id="56" type="ground"/>
 <tile id="57" type="wall"/>
 <tile id="58" type="wall"/>
 <tile id="59" type="openelectricalpanel"/>
 <tile id="60" type="openelectricalpanel"/>
 <tile id="61" type="surgicaltable"/>
 <tile id="62" type="surgicaltable"/>
 <tile id="63" type="surgicaltable"/>
 <tile id="64" type="surgicaltable"/>
 <tile id="66" type="ground"/>
 <tile id="67" type="ground"/>
 <tile id="68" type="ground"/>
 <tile id="69" type="ground"/>
 <tile id="70" type="brick"/>
 <tile id="71" type="scissors"/>
 <tile id="72" type="table"/>
 <tile id="73" type="table"/>
 <tile id="74" type="saw"/>
 <tile id="75" type="saw"/>
 <tile id="76" type="saw"/>
 <tile id="77" type="ground"/>
 <tile id="78" type="ground"/>
 <tile id="79" type="ground"/>
 <tile id="80" type="ground"/>
 <tile id="81" type="bone"/>
 <tile id="82" type="hole"/>
 <tile id="83" type="table"/>
 <tile id="84" type="table"/>
</tileset>
